name: score
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 7.1.7+15

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  flutter_local_notifications: ^6.0.0
  easy_localization: ^3.0.0
  smooth_star_rating: ^1.1.1
  font_awesome_flutter: ^9.1.0
  http: ^0.13.3
  shared_preferences: ^2.0.6
  flutter_launcher_icons: ^0.9.0
  url_launcher: ^5.1.1
  firebase_messaging: ^10.0.3
  firebase_core: ^1.3.0
  share: ^2.0.4
  flutter_spinkit: ^5.0.0
  flutter_page_transition: ^0.1.6
  flutter_html: ^2.1.0
  location: ^4.3.0
  carousel_slider: ^4.0.0
  polygon_clipper: ^1.0.2
  provider: ^5.0.0
  page_transition: ^2.0.2
  google_mobile_ads: ^0.13.2



flutter_icons:
  android: true
  ios: true
  image_path: "images/appIcon.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/langs/ar-EG.json
    - assets/langs/en-US.json
    - images/ring.mp3
    - images/alert.mp3
    - images/splash.png
    - images/scorelogo.png
    - images/saudi_arabia.png
    - images/basket_ball.png
    - images/list-right.png
    - images/list-left.png
    - images/saudiLogo.png
    - images/vollyBall.png
    - images/tensBall.png
    - images/pexels1.jpeg
    - images/pexels2.jpeg
    - images/playground.png
    - images/twitter.png
    - images/handBall.png
    - images/out.png
    - images/appIcon.png
    - images/logOut.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: cairo
      fonts:
        - asset: assets/fonts/Cairo-Bold.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
